name: analysis_server_lib
description: A library to access Dart's analysis server API.

version: 0.1.6
author: Devon Carew <devoncarew@google.com>
homepage: https://github.com/devoncarew/analysis_server_lib

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  logging: ^0.11.0
  path: ^1.0.0

dev_dependencies:
  html: ^0.14.0
  test: ^1.0.0
